server:
  port: 8005
spring:
  application:
    name: cloud-provider-payment

  cloud:
    consul:
      host: 47.101.223.154
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 127.0.0.1
