server:
  port: 85
spring:
  application:
    name: cloud-consumer-order-85
  cloud:
    consul:
      host: 47.101.223.154
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 127.0.0.1
