server:
  port: 8401

spring:
  application:
    name: cloud-sentinel-service
  cloud:
    nacos:
      discovery:
        # nacos服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置sentinel dashboard地址, 可以在运行sentinel时配置java参数，也可以在这里配置
        # java -DServer.port=8888 -Dcsp.sentinel.dashboard.server=localhost:8888 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard-1.7.2.jar
        dashboard: localhost:8080
        # 如果8080已经被占用，就会使用从8888逐个+1扫描，直到找到未占用的端口。
        port: 8888

management:
  endpoint:
    web:
      exposure:
        include: '*'
