server:
  port: 86

spring:
  application:
    name: cloud-consumer-feign-order-86

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
# \u8BBE\u7F6E\u6240\u6709\u7684\u5FAE\u670D\u52A1 \u8D85\u65F6\u914D\u7F6E
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: basic
# \u5355\u72EC\u8BBE\u7F6E\u67D0\u4E2A\u5FAE\u670D\u52A1\u7684\u8D85\u65F6\u914D\u7F6E
#feign:
#  client:
#    config:
#      server-A: # \u8BBE\u5B9Aserver-A \u670D\u52A1\u8C03\u7528\u7684\u8D85\u65F6\u8BBE\u7F6E
#        connectTimeout: 50000
#        readTimeout: 50000
#        loggerLevel: basic
#  \u5982\u679C\u4EE5\u4E0A\u90FD\u6CA1\u6709\u8BBE\u7F6E\u6B63\u786E\uFF0C\u8BBE\u7F6ERibbon \u7684\u8D85\u65F6\u914D\u7F6E\u4E5F\u662F\u751F\u6548\u7684\u3002\u56E0\u4E3AFeign \u5E95\u5C42\u8FD8\u662F\u4F7F\u7528Ribbon \u8D1F\u8F7D\u8C03\u7528\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3\u7684\u5FAE\u670D\u52A1\u7684\u3002
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
