server:
  port: 86

spring:
  application:
    name: cloud-consumer-feign-order-86

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
# 设置所有的微服务 超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000
        loggerLevel: basic
# 单独设置某个微服务的超时配置
#feign:
#  client:
#    config:
#      server-A: # 设定server-A 服务调用的超时设置
#        connectTimeout: 50000
#        readTimeout: 50000
#        loggerLevel: basic
#  如果以上都没有设置正确，设置Ribbon 的超时配置也是生效的。因为Feign 底层还是使用Ribbon 负载调用注册到注册中心的微服务的。
# 可是实践表明只有上面的才有效，下面连编译都没过
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
