server:
  port: 9527


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: payment_route
#          uri: http://localhost:8001
          uri: lb://cloud-provider-payment #配置动态路由的写法
          predicates:
            - Path=/payment/**
#            - Before=2020-02-05T15:10:03.685+08:00[Asia/Shanghai]
#            - After=2020-02-05T15:10:03.685+08:00[Asia/Shanghai]
#            - Cookie=username,passwd
#            - Header=X-Request-Id,\d+ #表示值为整数
#            - Host=localhost
#            - Method=GET
#            - Query=username, \d+ 表示query必须有username并且值还为整数