server:
  port: 83

spring:
  application:
    name: cloud-consumer-feign-hystrix

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000
        loggerLevel: basic