server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 47.101.223.154:2181

  datasource:
    druid:
      url: jdbc:mysql://47.101.223.154:3306/cloud?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      initial-size: 2
      min-idle: 2
      max-active: 4
      max-wait: 10000
      test-on-borrow: true
      test-while-idle: true
      # \u72B6\u6001\u76D1\u63A7
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        # \u76D1\u63A7\u8FC7\u6EE4\u5668
      web-stat-filter:
        enabled: true
        exclusions:
          - "*.js"
          - "*.gif"
          - "*.jpg"
          - "*.png"
          - "*.css"
          - "*.ico"
          - "/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.jxufe.entity